/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huang_jnidemo_MainActivity */

#ifndef _Included_com_huang_jnidemo_MainActivity
#define _Included_com_huang_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huang_jnidemo_MainActivity
 * Method:    getStringFromJNI
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_huang_jnidemo_MainActivity_getStringFromJNI
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
